/// Mapping from linear bit index (0-87) to the correct key in your piano widget.
/// w = whiteKeyPressed, b = blackKeyPressed
final List<MapEntry<bool, int>> bitToKeyMap = [
  MapEntry(true, 0),   // A0
  MapEntry(false, 0),  // Bb0
  MapEntry(true, 1),   // B0
  MapEntry(true, 2),   // C1
  MapEntry(false, 2),  // Db1
  MapEntry(true, 3),   // D1
  MapEntry(false, 3),  // Eb1
  MapEntry(true, 4),   // E1
  MapEntry(true, 5),   // F1
  MapEntry(false, 5),  // Gb1
  MapEntry(true, 6),   // G1
  MapEntry(false, 6),  // Ab1
  MapEntry(true, 7),   // A1
  MapEntry(false, 7),  // Bb1
  MapEntry(true, 8),   // B1
  MapEntry(true, 9),   // C2
  MapEntry(false, 9),  // Db2
  MapEntry(true, 10),  //  D2
  MapEntry(false, 10), //  Eb2
  MapEntry(true, 11),  //  E2
  MapEntry(true, 12),  //  F2
  MapEntry(false, 12), //  Gb2
  MapEntry(true, 13),  //  G2
  MapEntry(false, 13), //  Ab2
  MapEntry(true, 14),  //  A2
  MapEntry(false, 14), //  Bb2
  MapEntry(true, 15),  //  B2
  MapEntry(true, 16),  //  C3
  MapEntry(false, 16), //  Db3
  MapEntry(true, 17),  //  D3
  MapEntry(false, 17), //  Eb3
  MapEntry(true, 18),  //  E3
  MapEntry(true, 19),  //  F3
  MapEntry(false, 19), //  Gb3
  MapEntry(true, 20),  //  G3
  MapEntry(false, 20), //  Ab3
  MapEntry(true, 21),  //  A3
  MapEntry(false, 21), //  Bb3
  MapEntry(true, 22),  //  B3
  MapEntry(true, 23),  //  C4
  MapEntry(false, 23), //  Db4
  MapEntry(true, 24),  //  D4
  MapEntry(false, 24), //  Eb4
  MapEntry(true, 25),  //  E4
  MapEntry(true, 26),  //  F4
  MapEntry(false, 26), //  Gb4
  MapEntry(true, 27),  //  G4
  MapEntry(false, 27), //  Ab4
  MapEntry(true, 28),  //  A4
  MapEntry(false, 28), //  Bb4
  MapEntry(true, 29),  //  B4
  MapEntry(true, 30),  //  C5
  MapEntry(false, 30), //  Db5
  MapEntry(true, 31),  //  D5
  MapEntry(false, 31), //  Eb5
  MapEntry(true, 32),  //  E5
  MapEntry(true, 33),  //  F5
  MapEntry(false, 33), //  Gb5
  MapEntry(true, 34),  //  G5
  MapEntry(false, 34), //  Ab5
  MapEntry(true, 35),  //  A5
  MapEntry(false, 35), //  Bb5
  MapEntry(true, 36),  //  B5
  MapEntry(true, 37),  //  C6
  MapEntry(false, 37), //  Db6
  MapEntry(true, 38),  //  D6
  MapEntry(false, 38), //  Eb6
  MapEntry(true, 39),  //  E6
  MapEntry(true, 40),  //  F6
  MapEntry(false, 40), //  Gb6
  MapEntry(true, 41),  //  G6
  MapEntry(false, 41), //  Ab6
  MapEntry(true, 42),  //  A6
  MapEntry(false, 42), //  Bb6
  MapEntry(true, 43),  //  B6
  MapEntry(true, 44),  //  C7
  MapEntry(false, 44), //  Db7
  MapEntry(true, 45),  //  D7
  MapEntry(false, 45), //  Eb7
  MapEntry(true, 46),  //  E7
  MapEntry(true, 47),  //  F7
  MapEntry(false, 47), //  Gb7
  MapEntry(true, 48),  //  G7
  MapEntry(false, 48), //  Ab7
  MapEntry(true, 49),  //  A7
  MapEntry(false, 49), //  Bb7
  MapEntry(true, 50),  //  B7
  MapEntry(true, 51),  //  C8
  MapEntry(false, 51), //  Db8
  MapEntry(true, 52),  //  D8
  MapEntry(false, 52), //  Eb8
  MapEntry(true, 53),  //  E8
  MapEntry(true, 54),  //  F8
  MapEntry(false, 54), //  Gb8
  MapEntry(true, 55),  //  G8
  MapEntry(false, 55), //  Ab8
  MapEntry(true, 56),  //  A8
  MapEntry(false, 56), //  Bb8
  MapEntry(true, 57),  //  B8
  MapEntry(true, 58),  //  C9
];
