name: JacobsLadder
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - pip
  - pip:
      - Appium-Python-Client
      - pyautogui
      - python-rtmidi
      - selenium
